name: Release

on: workflow_dispatch

jobs:
  build:
    name: Build zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: captchafox
          path: ${{ github.workspace }}/src
          retention-days: 5
